language: cpp
dist: trusty
sudo: true
addons:
  apt:
    sources:
      - llvm-toolchain-trusty-5.0
      - ubuntu-toolchain-r-test
    packages:
      - clang-5.0
      - g++-7
      - valgrind

compiler:
    - gcc
    - clang
env:
  global:
    - CXX_FLAGS="-Wall -Wextra -Werror"
  matrix:
    - BUILD_TYPE=Debug
    - BUILD_TYPE=Release

install:
  # get cmake-3.10 and dump some debug info
  - mkdir -p ~/cmake
  - curl -ks https://cmake.org/files/v3.10/cmake-3.10.3-Linux-x86_64.sh -o cmake.sh
  - bash cmake.sh --skip-license --prefix="${HOME}/cmake"
  - export PATH=~/cmake/bin:$PATH
  - cmake --version

script:
  - if [ "$CXX" = "clang++" ]; then export CXX="clang++-5.0"; fi
  - if [ "$CXX" = "g++" ]    ; then export CXX="g++-7";       fi
  - ${CXX} --version
  - mkdir -p build
  - cd build
  - cmake ${CMAKE_OPTIONS} -DCMAKE_CXX_FLAGS="${CXX_FLAGS}" -DCMAKE_BUILD_TYPE=${BUILD_TYPE} -DMEMORYCHECK_SUPPRESSIONS_FILE="${TRAVIS_BUILD_DIR}/resources/valgrind.supp" ..
  - make -j3 VERBOSE=1
  - ctest -T memcheck -j3
  - cat ${TRAVIS_BUILD_DIR}/build/Testing/Temporary/MemoryChecker.*.log > out && cat out
  - test ! -s out
